### ISSUE TITLE
Every other page of the constitution is upside down in the PDF download

### ISSUE THREAD

**Issue by meshy** [PyconUK/ukpa-constitution#7]
As the title states, every other page is upside down! I imagine this is for the purposes of printing the document, but makes it a challenging read on a computer :joy: 

Would it make sense to offer two versions on the [releases page](https://github.com/UKPythonAssociation/ukpa-constitution/releases)? One for print, and one suitable for digital reading?

**Comment by meatballs** [comment]
Yes, it's designed to be printed as an A5 booklet to save a little paper. I'll add another version when I get a moment.

**Comment by meshy** [comment]
Thank you! There's no rush though! :)

**Comment by meatballs** [comment]
Done

**Comment by meshy** [comment]
Wow that was quick! Thank you very much!
